<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class RisksTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('risks')->insert([
            [
                'id' => 1,
                'nama_kegiatan' => 'Manajemen Sistem Informasi Rumah Sakit',
                'tujuan_kegiatan' => 'Menjamin ketersediaan dan keamanan sistem informasi rumah sakit',
                'area_lokasi' => 'Data Center',
                'kode_risiko' => 'TI001',
                'risiko' => 'Sistem informasi tidak dapat diakses',
                'sebab_1' => 'Terjadinya gangguan listrik mendadak',
                'sebab_2' => 'Kegagalan hardware server',
                'sebab_3' => 'Tidak adanya redundansi jaringan',
                'sebab_4' => 'Backup data tidak dilakukan secara rutin',
                'sebab_5' => 'Kurangnya pemeliharaan perangkat TI',
                'dampak' => 'Layanan medis terganggu karena tidak dapat mengakses data pasien',
                'pernyataan_risiko' => 'Gangguan pada sistem informasi yang menyebabkan layanan rumah sakit tidak dapat berjalan optimal',
                'pengendalian_saat_ini' => 'Penggunaan UPS dan jadwal maintenance berkala',
                'analisa_dampak' => 3,
                'analisa_probabilitas' => 2,
                'analisa_concate' => 32,
                'skor' => 6,
                'peringkat_risiko' => 'Sedang',
                'perlu_penanganan' => true,
                'hindari_risiko' => false,
                'cegah_kerugian' => true,
                'reduksi_kerugian' => true,
                'segregasi' => false,
                'contractual_transfer' => false,
                'rencana_penanganan' => 'Implementasi backup server, redundansi jaringan, dan SOP pemulihan layanan',
                'pembiayaan_risiko' => 'Rp 5.000.000',
                'created_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-15 07:22:57'),
                'updated_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-15 07:22:57'),
            ],
            [
                'id' => 2,
                'nama_kegiatan' => 'Pengelolaan Laporan Keuangan Rumah Sakit',
                'tujuan_kegiatan' => 'Memastikan laporan keuangan tersusun tepat waktu dan akurat',
                'area_lokasi' => 'Ruang Keuangan',
                'kode_risiko' => 'FIN001',
                'risiko' => 'Terjadinya kesalahan pencatatan transaksi keuangan',
                'sebab_1' => 'Dokumen pendukung tidak lengkap',
                'sebab_2' => 'Staf akuntansi kurang teliti saat entri data',
                'sebab_3' => 'Sistem informasi akuntansi belum terintegrasi',
                'sebab_4' => 'Rekonsiliasi tidak dilakukan secara berkala',
                'sebab_5' => 'Kurangnya pelatihan bagi staf',
                'dampak' => 'Laporan keuangan menjadi tidak akurat dan memperlambat pengambilan keputusan',
                'pernyataan_risiko' => 'Kesalahan dalam pencatatan transaksi menyebabkan ketidaktepatan laporan keuangan',
                'pengendalian_saat_ini' => 'Rekonsiliasi mingguan dan double-check manual sebelum laporan disahkan',
                'analisa_dampak' => 3,
                'analisa_probabilitas' => 2,
                'analisa_concate' => 32,
                'skor' => 6,
                'peringkat_risiko' => 'Sedang',
                'perlu_penanganan' => true,
                'hindari_risiko' => false,
                'cegah_kerugian' => true,
                'reduksi_kerugian' => true,
                'segregasi' => false,
                'contractual_transfer' => false,
                'rencana_penanganan' => 'Implementasi sistem akuntansi terintegrasi dan pelatihan rutin staf',
                'pembiayaan_risiko' => 'Rp 8.000.000',
                'created_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-15 07:32:02'),
                'updated_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-15 07:32:02'),
            ],
            [
                'id' => 3,
                'nama_kegiatan' => 'Pengelolaan Distribusi Obat dan Alat Kesehatan',
                'tujuan_kegiatan' => 'Menjamin proses distribusi obat dan alat kesehatan berjalan tepat waktu dan aman',
                'area_lokasi' => 'Gudang Obat / Area Distribusi',
                'kode_risiko' => 'LOG002',
                'risiko' => 'Kerusakan obat/alkes selama proses distribusi',
                'sebab_1' => 'Penyimpanan tidak sesuai suhu standar',
                'sebab_2' => 'Kendaraan distribusi tidak memenuhi standar',
                'sebab_3' => 'Tidak dilakukan pemeriksaan kondisi barang sebelum dikirim',
                'sebab_4' => 'SOP distribusi tidak dijalankan dengan konsisten',
                'sebab_5' => 'Kurangnya pelatihan petugas distribusi',
                'dampak' => 'Pasien menerima obat/alkes yang tidak layak dan membahayakan keselamatan',
                'pernyataan_risiko' => 'Kerusakan obat dan alat kesehatan selama proses distribusi dapat menyebabkan risiko keselamatan pasien',
                'pengendalian_saat_ini' => 'Pemeriksaan visual sebelum distribusi + catatan suhu manual',
                'analisa_dampak' => 4,
                'analisa_probabilitas' => 3,
                'analisa_concate' => 43,
                'skor' => 12,
                'peringkat_risiko' => 'Tinggi',
                'perlu_penanganan' => true,
                'hindari_risiko' => false,
                'cegah_kerugian' => true,
                'reduksi_kerugian' => true,
                'segregasi' => false,
                'contractual_transfer' => false,
                'rencana_penanganan' => 'Pengadaan kendaraan distribusi khusus, implementasi log suhu otomatis, pelatihan petugas',
                'pembiayaan_risiko' => 'Rp 10.000.000',
                'created_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-17 17:42:43'),
                'updated_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-17 17:42:43'),
            ],
            [
                'id' => 4,
                'nama_kegiatan' => 'Pengelolaan Rekrutmen dan Seleksi Pegawai',
                'tujuan_kegiatan' => 'Menjamin proses rekrutmen berjalan tepat waktu dengan kandidat yang kompeten',
                'area_lokasi' => 'Ruang HR / Ruang Interview',
                'kode_risiko' => 'HR001',
                'risiko' => 'Keterlambatan pemenuhan kebutuhan tenaga kerja',
                'sebab_1' => 'Proses persetujuan formasi yang memakan waktu',
                'sebab_2' => 'Jumlah pelamar yang memenuhi syarat terbatas',
                'sebab_3' => 'Jadwal wawancara yang tidak konsisten',
                'sebab_4' => 'Kurangnya koordinasi antara HR dan kepala unit',
                'sebab_5' => 'Proses administrasi penerimaan yang tidak efisien',
                'dampak' => 'Pekerjaan operasional terganggu karena kekurangan tenaga',
                'pernyataan_risiko' => 'Keterlambatan pengisian posisi kosong dapat menghambat kelancaran operasional rumah sakit',
                'pengendalian_saat_ini' => 'Penyusunan database talent pool dan koordinasi rutin dengan unit terkait',
                'analisa_dampak' => 3,
                'analisa_probabilitas' => 3,
                'analisa_concate' => 33,
                'skor' => 9,
                'peringkat_risiko' => 'Sedang',
                'perlu_penanganan' => true,
                'hindari_risiko' => false,
                'cegah_kerugian' => true,
                'reduksi_kerugian' => true,
                'segregasi' => false,
                'contractual_transfer' => false,
                'rencana_penanganan' => 'Digitalisasi proses rekrutmen, perjanjian kerja sama dengan penyedia tenaga outsourcing',
                'pembiayaan_risiko' => 'Rp 7.500.000',
                'created_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-17 17:52:48'),
                'updated_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-17 17:52:48'),
            ],
            [
                'id' => 5,
                'nama_kegiatan' => 'Manajemen Informasi Publikasi Kesehatan',
                'tujuan_kegiatan' => 'Menjamin penyampaian informasi kesehatan yang akurat kepada masyarakat',
                'area_lokasi' => 'Ruang Humas dan Pemasaran',
                'kode_risiko' => 'HUM001',
                'risiko' => 'Penyebaran informasi kesehatan yang tidak akurat',
                'sebab_1' => 'Kurangnya verifikasi informasi sebelum dipublikasikan',
                'sebab_2' => 'Staf humas tidak memiliki latar belakang medis',
                'sebab_3' => 'Tekanan untuk segera merilis informasi',
                'sebab_4' => 'Kurangnya koordinasi dengan tim medis',
                'sebab_5' => 'Tidak adanya SOP standar konten kesehatan',
                'dampak' => 'Masyarakat menerima informasi salah tentang kesehatan',
                'pernyataan_risiko' => 'Kesalahan informasi dapat mengganggu pelayanan medis dan kepercayaan publik',
                'pengendalian_saat_ini' => 'Proses verifikasi konten oleh dokter atau tenaga medis sebelum publikasi',
                'analisa_dampak' => 3,
                'analisa_probabilitas' => 3,
                'analisa_concate' => 33,
                'skor' => 9,
                'peringkat_risiko' => 'Sedang',
                'perlu_penanganan' => true,
                'hindari_risiko' => false,
                'cegah_kerugian' => true,
                'reduksi_kerugian' => true,
                'segregasi' => false,
                'contractual_transfer' => false,
                'rencana_penanganan' => 'Membuat SOP verifikasi informasi kesehatan, pelatihan staf humas terkait dasar medis, serta koordinasi rutin dengan tim medis',
                'pembiayaan_risiko' => 'Rp 6.500.000',
                'created_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 17:02:22'),
                'updated_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 17:02:57'),
            ],
            [
                'id' => 6,
                'nama_kegiatan' => 'Kegagalan Pengelolaan Reputasi Rumah Sakit',
                'tujuan_kegiatan' => 'Menjaga citra positif rumah sakit di mata publik',
                'area_lokasi' => 'Ruang Humas dan Pemasaran',
                'kode_risiko' => 'HUM-NK001',
                'risiko' => 'Krisis reputasi akibat isu negatif di media',
                'sebab_1' => 'Kurangnya monitoring media secara real-time',
                'sebab_2' => 'Tidak ada strategi komunikasi krisis',
                'sebab_3' => 'Terlambat menanggapi isu publik',
                'sebab_4' => 'Minimnya hubungan baik dengan media massa',
                'sebab_5' => 'Pengelolaan konten media sosial yang kurang tepat',
                'dampak' => 'Citra rumah sakit menurun di mata masyarakat',
                'pernyataan_risiko' => 'Menurunnya kepercayaan pasien terhadap layanan',
                'pengendalian_saat_ini' => 'Membuat tim komunikasi krisis dan SOP penanganan media',
                'analisa_dampak' => 4,
                'analisa_probabilitas' => 5,
                'analisa_concate' => 45,
                'skor' => 20,
                'peringkat_risiko' => 'Sangat Tinggi',
                'perlu_penanganan' => true,
                'hindari_risiko' => true,
                'cegah_kerugian' => false,
                'reduksi_kerugian' => true,
                'segregasi' => true,
                'contractual_transfer' => true,
                'rencana_penanganan' => 'Membentuk tim manajemen krisis, memperkuat hubungan dengan media, dan monitoring media 24/7',
                'pembiayaan_risiko' => 'Rp 15.000.000',
                'created_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 17:09:19'),
                'updated_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 17:09:19'),
            ],
            [
                'id' => 7,
                'nama_kegiatan' => 'Pengembangan Aplikasi Layanan Pasien',
                'tujuan_kegiatan' => 'Meningkatkan aksesibilitas layanan rumah sakit melalui aplikasi pasien',
                'area_lokasi' => 'Divisi Pengembangan Layanan',
                'kode_risiko' => 'DEV001',
                'risiko' => 'Aplikasi pasien mengalami bug pada fitur pendaftaran',
                'sebab_1' => 'Pengujian aplikasi tidak menyeluruh',
                'sebab_2' => 'Kurangnya dokumentasi teknis',
                'sebab_3' => 'Deadline pengembangan terlalu ketat',
                'sebab_4' => 'Tidak adanya UAT (User Acceptance Test) sebelum rilis',
                'sebab_5' => 'Tim pengembangan kekurangan personil QA',
                'dampak' => 'Pasien kesulitan mendaftar layanan',
                'pernyataan_risiko' => 'Kepercayaan pasien terhadap layanan digital berkurang',
                'pengendalian_saat_ini' => 'Testing internal sebelum rilis dan evaluasi pasca implementasi',
                'analisa_dampak' => 2,
                'analisa_probabilitas' => 2,
                'analisa_concate' => 22,
                'skor' => 4,
                'peringkat_risiko' => 'Rendah',
                'perlu_penanganan' => true,
                'hindari_risiko' => false,
                'cegah_kerugian' => false,
                'reduksi_kerugian' => true,
                'segregasi' => true,
                'contractual_transfer' => false,
                'rencana_penanganan' => 'Melakukan UAT, menambah personil QA, dan jadwal revisi rutin',
                'pembiayaan_risiko' => 'Rp 3.000.000',
                'created_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 17:22:10'),
                'updated_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 17:22:10'),
            ],
            [
                'id' => 8,
                'nama_kegiatan' => 'Pemeliharaan Sistem Jaringan',
                'tujuan_kegiatan' => 'Menjaga stabilitas jaringan dan konektivitas internal rumah sakit',
                'area_lokasi' => 'Divisi Teknologi Informasi',
                'kode_risiko' => 'IT001',
                'risiko' => 'Gangguan minor pada koneksi jaringan lokal',
                'sebab_1' => 'Kabel jaringan yang sudah lama digunakan',
                'sebab_2' => 'Switch mengalami restart otomatis',
                'sebab_3' => 'Konfigurasi IP tidak terupdate',
                'sebab_4' => 'Kurangnya monitoring real-time jaringan',
                'sebab_5' => 'Tidak ada jadwal maintenance rutin',
                'dampak' => 'Akses ke sistem informasi sedikit terhambat',
                'pernyataan_risiko' => 'Karyawan perlu waktu tambahan untuk mengakses aplikasi',
                'pengendalian_saat_ini' => 'Dilakukan pengecekan perangkat setiap minggu dan log monitoring jaringan',
                'analisa_dampak' => 2,
                'analisa_probabilitas' => 2,
                'analisa_concate' => 22,
                'skor' => 4,
                'peringkat_risiko' => 'Rendah',
                'perlu_penanganan' => true,
                'hindari_risiko' => false,
                'cegah_kerugian' => true,
                'reduksi_kerugian' => true,
                'segregasi' => false,
                'contractual_transfer' => false,
                'rencana_penanganan' => 'Melakukan maintenance rutin, update konfigurasi, dan mengganti kabel lama',
                'pembiayaan_risiko' => 'Rp 2.500.000',
                'created_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 17:40:18'),
                'updated_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 17:40:18'),
            ],
                        [
                'id' => 9,
                'nama_kegiatan' => 'Kesalahan Pengkodean Diagnosis pada Klaim',
                'tujuan_kegiatan' => 'Menjamin keakuratan kode diagnosis sesuai standar INA-CBGs',
                'area_lokasi' => 'Divisi Keuangan dan Akuntansi',
                'kode_risiko' => 'KEU002',
                'risiko' => 'Pengkodean diagnosis tidak sesuai standar klaim',
                'sebab_1' => 'Kurangnya pemahaman petugas coding',
                'sebab_2' => 'Tidak ada pelatihan berkala ICD-10',
                'sebab_3' => 'Tidak adanya sistem validasi otomatis',
                'sebab_4' => 'Dokter tidak detail dalam pencatatan rekam medis',
                'sebab_5' => 'Terbatasnya waktu verifikasi',
                'dampak' => 'Klaim ditolak atau dikurangi nilainya',
                'pernyataan_risiko' => 'Kesalahan pengkodean diagnosis dapat menyebabkan kerugian finansial bagi rumah sakit',
                'pengendalian_saat_ini' => 'Audit internal klaim sebelum pengiriman',
                'analisa_dampak' => 4,
                'analisa_probabilitas' => 5,
                'analisa_concate' => 45,
                'skor' => 20,
                'peringkat_risiko' => 'Sangat Tinggi',
                'perlu_penanganan' => true,
                'hindari_risiko' => true,
                'cegah_kerugian' => true,
                'reduksi_kerugian' => true,
                'segregasi' => false,
                'contractual_transfer' => false,
                'rencana_penanganan' => 'Menyediakan pelatihan coder rutin dan sistem validasi otomatis ICD-10',
                'pembiayaan_risiko' => 'Rp 30.000.000',
                'created_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 18:00:54'),
                'updated_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 18:00:54'),
                'tipe_risiko' => 'klinis',
                'company_id' => 1,
                'divisi_id' => 2,
                'tahun' => 2025,
            ],

            // Risiko 10
            [
                'id' => 10,
                'nama_kegiatan' => 'Keterlambatan Integrasi Sistem Layanan Medis',
                'tujuan_kegiatan' => 'Memastikan layanan klinis terintegrasi dengan sistem digital secara tepat waktu',
                'area_lokasi' => 'Divisi Pengembangan Layanan',
                'kode_risiko' => 'CLIN-DEV002',
                'risiko' => 'Integrasi sistem medis dengan aplikasi pasien tertunda',
                'sebab_1' => 'Koordinasi kurang antara tim IT dan tim medis',
                'sebab_2' => 'Keterbatasan resource teknis',
                'sebab_3' => 'Ketergantungan pada vendor eksternal',
                'sebab_4' => 'Perubahan kebutuhan di tengah proyek',
                'sebab_5' => 'Anggaran terbatas untuk modul tambahan',
                'dampak' => 'Layanan pasien tidak bisa menggunakan sistem digital penuh',
                'pernyataan_risiko' => 'Keterlambatan integrasi sistem layanan medis dapat mengurangi efisiensi pelayanan medis',
                'pengendalian_saat_ini' => 'Monitoring proyek rutin dan laporan bulanan',
                'analisa_dampak' => 3,
                'analisa_probabilitas' => 3,
                'analisa_concate' => 33,
                'skor' => 9,
                'peringkat_risiko' => 'Sedang',
                'perlu_penanganan' => true,
                'hindari_risiko' => true,
                'cegah_kerugian' => true,
                'reduksi_kerugian' => true,
                'segregasi' => false,
                'contractual_transfer' => false,
                'rencana_penanganan' => 'Menambah resource teknis, menetapkan PIC koordinasi, dan evaluasi kebutuhan lebih awal',
                'pembiayaan_risiko' => 'Rp 6.000.000',
                'created_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 18:16:36'),
                'updated_at' => Carbon::createFromFormat('Y-m-d H:i:s', '2025-08-23 18:16:36'),
                'tipe_risiko' => 'klinis',
                'company_id' => 3,
                'divisi_id' => 6,
                'tahun' => 2024,
            ],

        ]);
    }
}